### ISSUE TITLE
pre-check discrete or continuous action by algorithms

### ISSUE THREAD

**Issue by HanbumKo** [kakaoenterprise/JORLDY#41]
**Is your feature request related to a problem? Please describe.**
Hi, thank you for sharing this project.
For now it seems DQN doesn't check discrete or continuous in advance. When I change `dqn.cartpole` config
```
env = {
    "name":"cartpole",
    "render":False,
}
```
to
```
env = {
    "name":"cartpole",
    "render":False,
    "mode":"continuous",
}
```
it doesn't give any errors and isn't trained well. Since DQN is an algorithm for discrete action and buffer gives integer actions so continuous [Cartpole env](https://github.com/kakaoenterprise/JORLDY/blob/master/jorldy/core/env/gym_env.py#L66-L67) only run `action = 1`. (and I didn't really look into that other algorithms check the actions, but DQN doesn't)

**Describe the solution you'd like**
It might be possible to insert `assert` statement in each algorithm codes.

**Describe alternatives you've considered**
x

**Additional context**
x

**Comment by ramanuzan** [comment]
Thank you for contributing our project. fixed issue. #60
