### ISSUE TITLE
Errors when running Drone_Challenge

### ISSUE THREAD

**Issue by pnltoen** [kakaoenterprise/JORLDY#54]
**Describe the bug**
1. Not running mlagents until I stalled hiredis
2. DroneDelivery env error, I think it's corrupted.

**To Reproduce**
pip install -r requirements.txt
python sync_distributed_train.py --config=config.ppo.drone_delivery_mlagent

**Expected behavior**

First, After I had installed requirements.txt I followed the commands "python sync_distributed_train.py --config=config.ppo.drone_delivery_mlagent"
Then I saw **"redis-py works best with hiredis please consider installing"** in my case it's not causing any problem to run mlagents.
but one on my friend couldn't run it until he installed hiredis. 

Second, When I run mlagents. I could barely see Drone, Destination points.  (please see the pic I attached)
By overwriting files with [this](https://drive.google.com/drive/folders/1FW3LrUqabmx4ovT4gi0pOvF3PdkH7tdn) I could solve the problem.

Please check these errors. Thanks

**Screenshots**
![image](https://user-images.githubusercontent.com/85833046/142410103-60574ca9-5aa4-4275-ad07-5474607d095f.png)

**Development Env. (OS, version, libraries):**
Windows 10, Anaconda, Python3.8.8

**Comment by leonard-q** [comment]
We updated drone delivery env for Mac which had issue and tested drone delivery env for all the os. The env worked well in all the envs, so we close this issue
