### ISSUE TITLE
Couldn't launch the "Server/DroneDelivery"

### ISSUE THREAD

**Issue by zenoengine** [kakaoenterprise/JORLDY#55]
**Describe the bug**
```sh
mlagents_envs.exception.UnityEnvironmentException:

Couldn't launch the ./core/env/mlagents/DroneDelivery/Server/DroneDelivery environment. 
Provided filename does not match any environments.
```

**To Reproduce**

```sh
# docker
docker build -t jorldy -f ./docker/Dockerfile .
docker run -it --rm --name jorldy -v `pwd`:/JORLDY jorldy /bin/bash

python sync_distributed_train.py --config=config.ppo.drone_delivery_mlagent
```

**Expected behavior**

**Screenshots**

**Development Env. (OS, version, libraries):**
Ubuntu 18.04.5 LTS", 
mlagents-envs           0.26.0

**Additional context**

**Comment by leonard-q** [comment]
ML-Agents server build uses env without rendering. In this case, the mlagents env get only black image data as image obs. Therefore, we separated Linux build and Server build. The drone env uses image obs, so we didn't append the Server build in DroneDelivery. However, we realized that using no graphics option with Linux build is same with Server build. Therefore, we removed all the Server build of mlagent envs in #58 . Thanks to your issue, we could get an idea that using mlagent envs in both ordinary Linux and Linux server with single mlagent Linux build. 
With this modification, you can run dronedelivery in server.
